### ISSUE TITLE
in the loop of building web pack

### ISSUE THREAD

**Issue by ra312** [mldangelo/personal-site#179]
Dear Michael D'Angelo

After I run npm dev run I get stuck in the loop

                             main.js  4.51 MiB    main  [emitted]  main
Entrypoint main = main.js
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    74541159a9c80e617eb5.hot-update.json  44 bytes          [emitted]  
                              index.html  1.42 MiB       0             
    Entrypoint undefined = index.html
ℹ ｢wdm｣: Compiled successfully.
127.0.0.1 - - [02/Mar/2019:20:03:58 +0000] "GET /753a9cb0e0da351539cf.hot-update.json HTTP/1.1" 200 35 "http://localhost:7999/about" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
ℹ ｢wdm｣: Compiling...
webpack building...
Webpack finished compiling.
webpack built 7a62584ddf354df17bb2 in 173ms
ℹ ｢wdm｣: Version: webpack 4.29.6
Time: 173ms
Built at: 03/02/2019 8:03:58 PM
                               Asset      Size  Chunks             Chunk Names
11bc604996bc35f9b7e4.hot-update.json  44 bytes          [emitted]  
3cc772757a06b386c775.hot-update.json  35 bytes          [emitted]  
                          index.html  2.22 KiB          [emitted]  
                             main.js  4.51 MiB    main  [emitted]  main
Entrypoint main = main.js
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    11bc604996bc35f9b7e4.hot-update.json  44 bytes          [emitted]  
                              index.html  1.42 MiB       1             
    Entrypoint undefined = index.html
ℹ ｢wdm｣: Compiled successfully.
127.0.0.1 - - [02/Mar/2019:20:03:58 +0000] "GET /3cc772757a06b386c775.hot-update.json HTTP/1.1" 200 35 "http://localhost:7999/about" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
ℹ ｢wdm｣: Compiling...
webpack building...
Webpack finished compiling.
webpack built 0072b83f936d970ce0bf in 154ms
ℹ ｢wdm｣: Version: webpack 4.29.6
Time: 154ms
Built at: 03/02/2019 8:04:11 PM
                               Asset      Size  Chunks             Chunk Names
51014b7f17af7aedc7d0.hot-update.json  44 bytes          [emitted]  
7a62584ddf354df17bb2.hot-update.json  35 bytes          [emitted]  
                          index.html  2.22 KiB          [emitted]  
                             main.js  4.51 MiB    main  [emitted]  main
Entrypoint main = main.js
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    51014b7f17af7aedc7d0.hot-update.json  44 bytes          [emitted]  
                              index.html  1.42 MiB       0             
    Entrypoint undefined = index.html
ℹ ｢wdm｣: Compiled successfully.
127.0.0.1 - - [02/Mar/2019:20:04:11 +0000] "GET /7a62584ddf354df17bb2.hot-update.json HTTP/1.1" 200 35 "http://localhost:7999/about" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
ℹ ｢wdm｣: Compiling...
webpack building...
Webpack finished compiling.
webpack built 68c9590cca3fa5d5a59c in 230ms
ℹ ｢wdm｣: Version: webpack 4.29.6
Time: 230ms
Built at: 03/02/2019 8:04:52 PM
                               Asset      Size  Chunks             Chunk Names
0072b83f936d970ce0bf.hot-update.json  35 bytes          [emitted]  
bb80e130a705a7680744.hot-update.json  44 bytes          [emitted]  
                          index.html  2.22 KiB          [emitted]  
                             main.js  4.51 MiB    main  [emitted]  main
Entrypoint main = main.js
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    bb80e130a705a7680744.hot-update.json  44 bytes          [emitted]  
                              index.html  1.42 MiB       1             
    Entrypoint undefined = index.html
ℹ ｢wdm｣: Compiled successfully.
127.0.0.1 - - [02/Mar/2019:20:04:52 +0000] "GET /0072b83f936d970ce0bf.hot-update.json HTTP/1.1" 200 35 "http://localhost:7999/about" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
ℹ ｢wdm｣: Compiling...
webpack building...
Webpack finished compiling.
webpack built 178f0b2bd94a21b07ea3 in 199ms
ℹ ｢wdm｣: Version: webpack 4.29.6
Time: 199ms
Built at: 03/02/2019 8:05:15 PM
                               Asset      Size  Chunks             Chunk Names
68c9590cca3fa5d5a59c.hot-update.json  35 bytes          [emitted]  
d84f994b188ad4d4241e.hot-update.json  44 bytes          [emitted]  
                          index.html  2.22 KiB          [emitted]  
                             main.js  4.51 MiB    main  [emitted]  main
Entrypoint main = main.js
Child html-webpack-plugin for "index.html":
                                   Asset      Size  Chunks             Chunk Names
    d84f994b188ad4d4241e.hot-update.json  44 bytes          [emitted]  
                              index.html  1.42 MiB       0             
    Entrypoint undefined = index.html
ℹ ｢wdm｣: Compiled successfully.
127.0.0.1 - - [02/Mar/2019:20:05:15 +0000] "GET /68c9590cca3fa5d5a59c.hot-update.json HTTP/1.1" 200 35 "http://localhost:7999/about" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:28 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/stats" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:30 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/projects" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:30 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/stats" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:31 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/contact" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:32 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/stats" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:32 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/projects" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:33 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/resume" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:33 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/about" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:34 +0000] "GET /images/me_icon.jpg HTTP/1.1" 304 - "http://localhost:7999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"
127.0.0.1 - - [02/Mar/2019:20:05:34 +0000] "GET /__webpack_hmr HTTP/1.1" 200 - "http://localhost:7999/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15"

**Comment by mldangelo** [comment]
Hi @ra312, sorry to hear that it's not working. Did you make any modifications to the project? If so, can you link me to your repository? Can you share your operating system, node and npm versions? Thank you.

**Comment by ra312** [comment]
Hi @mldangelo 
The initial loop problem resolved itself (somewhat miraculously).
My OS, node and npm versions are below.
System Version: macOS 10.14.3 (18D109)
npm --version 
6.7.0
node --version
v11.10.1

I successfully launched localhost at the port 7999.
However, after the deployment to my GitHub domain, I don't see the website, but the README.md page. I tried several times yesterday without success. Would you have an idea what's going on?
Feel free to request any possible additional information.
Many thanks, @ra312.
