### ISSUE TITLE
Getting error when deploying with heroku server

### ISSUE THREAD

**Issue by jainAdijain** [mldangelo/personal-site#206]
While using this with heroku server i am unable to load your website, 
the error i am getting is `Uncaught SyntaxError: Unexpected token '<'`

The steps I had followed to deploy the code in Heroku is taken from [this ](https://www.freecodecamp.org/news/how-to-deploy-a-nodejs-app-to-heroku-from-github-without-installing-heroku-on-your-machine-433bec770efe/)article but unable to view the pages, need help what more can be done to do this.

**Comment by MatthewYee92** [comment]
Did you ever find a solution to this? Having the same problem on my end.

**Comment by typpo** [comment]
@MatthewYee92 Do you have a full stack trace for this error?

**Comment by arpitjain2602** [comment]
I only found that error means that it was receiving an html file but was expecting a JSON. Don't have a full stack trace. I hosted this on git pages. Cheers!

**Comment by thuyvy3110** [comment]
Hi, the same problem I had as same as **jainAdijain**

- For the error "Uncaught SyntaxError: Unexpected token '<' "

I updated index.tpl.html as below, move  the <head> before <meta ...> tag

<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en">
  **<head>**
    <meta http-equiv="content-type" content="text/html;charset=utf-8">

p/s: use https://jsonformatter.org/html-validator to check, you can see the error stay at <head> tag

- To deploy the code in **Heroku**, change the script in package.json

"**scripts**": {
    "build-app": "node -r @babel/register  ./node_modules/webpack/bin/webpack --config ./webpack/webpack.production.config.js --progress --profile --colors && rimraf ./dist && mv ./tmp ./dist",
    "build-dev": "rimraf ./dist && babel-node ./node_modules/webpack/bin/webpack --config ./webpack/webpack.config.js --progress --profile --colors",
    "clean": "rimraf ./dist && rimraf ./tmp",
    "lint": "./node_modules/.bin/eslint app server test webpack",
    "test": "./node_modules/mocha/bin/mocha --exit --require @babel/register ./test/test.js",
    "start": "nodemon server/server.js --ignore app/ --ignore test/ --exec babel-node",
    "parse-routes": "node -r @babel/register parseRoutes.js",
    "predeploy": "npm run build && cp -r public/* dist/ && cp dist/index.html dist/404.html && npm run parse-routes",
    "deploy": "gh-pages -d dist",
    "build": "npm run build-app && cp -r public/* dist/ && cp dist/index.html dist/404.html && npm run parse-routes"
  },

- Then, update **server.js** file, change ../public to ../dist

app.use(basePath, express.static(path.join(__dirname, '../**dist**')));

**Comment by DeKal** [comment]
@thuyvy3110 Thanks, it solves my problem :D 
https://adasassad.herokuapp.com/

**Comment by typpo** [comment]
Thanks for the solution @thuyvy3110, should be fixed on master now
