### ISSUE TITLE
error when running npm run deploy 

### ISSUE THREAD

**Issue by jainAdijain** [mldangelo/personal-site#210]
![image](https://user-images.githubusercontent.com/27722458/67148711-2cc10280-f2c0-11e9-931a-881d921ecceb.png)

**Comment by jainAdijain** [comment]
![image](https://user-images.githubusercontent.com/27722458/67148911-97733d80-f2c2-11e9-9179-dec5722e94aa.png)

**Comment by jainAdijain** [comment]
![image](https://user-images.githubusercontent.com/27722458/67148931-ce495380-f2c2-11e9-851d-63b7e0009870.png)

**Comment by MatthewYee92** [comment]
I am getting the same error here on my end. I also am getting an unexpected token '<' whenever I change to production. Any idea on why that is happening?

**Comment by typpo** [comment]
This should be fixed by #212
