### ISSUE TITLE
Size exceeds 100mb

### ISSUE THREAD

**Issue by sakethbachu** [mldangelo/personal-site#244]
Github says it cant push 1gb, is there any work around for this? The node modules are heavy.

**Comment by mldangelo** [comment]
Hi @sakethbachu, I don't have full context into your problem, but it sounds like you checked your `node_modules` folder into your repository. While you need to have `node_modules` available to build the app, checking the `node_modules` folder in is not recommended (see the github recommended `.gitignore` for node projects [here](https://github.com/github/gitignore/blob/master/Node.gitignore#L41). There's a lot of great pre-existing literature on this topic. I recommend reading through [this](https://stackoverflow.com/a/52687208) discussion on stack overlow (and pay attention to the answer dates). After you finish reading, take a look at the npm docs as well ([here](https://docs.npmjs.com/configuring-npm/package-lock-json.html)). 

If you accidentally committed `node_modules` and then deleted them but you're still getting this issue, take a look at [this](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository) to remove `node_modules` from your git history. Best of luck, please let me know if there is more I can do to help.

**Comment by sakethbachu** [comment]
Thank you for your response.
