### ISSUE TITLE
Deployment: pageerror at /personal-site/: SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by Kamel773** [mldangelo/personal-site#246]
> personal-site@2.1.0 postbuild /Users/kamel/Desktop/MYWebPage/Production
> react-snap

🔥  pageerror at /personal-site/: SyntaxError: Unexpected token '<'

✅  crawled 1 out of 1 (/personal-site/)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! personal-site@2.1.0 postbuild: `react-snap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the personal-site@2.1.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kamel/.npm/_logs/2020-09-26T01_36_25_030Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! personal-site@2.1.0 predeploy: `npm run build && cp -r public/* build/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the personal-site@2.1.0 predeploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kamel/.npm/_logs/2020-09-26T01_36_25_067Z-debug.log

**Comment by Kamel773** [comment]
the file : /Users/kamel/.npm/_logs/2020-09-26T01_36_25_067Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.7.0
3 info using node@v11.12.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle personal-site@2.1.0~predeploy: personal-site@2.1.0
6 verbose lifecycle personal-site@2.1.0~predeploy: unsafe-perm in lifecycle true
7 verbose lifecycle personal-site@2.1.0~predeploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/kamel/Desktop/MYWebPage/Production/node_modules/.bin:/Users/kamel/.rvm/gems/ruby-2.4.1/bin:/Users/kamel/.rvm/gems/ruby-2.4.1@global/bin:/Users/kamel/.rvm/rubies/ruby-2.4.1/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/kamel/.rvm/bin
8 verbose lifecycle personal-site@2.1.0~predeploy: CWD: /Users/kamel/Desktop/MYWebPage/Production
9 silly lifecycle personal-site@2.1.0~predeploy: Args: [ '-c', 'npm run build && cp -r public/* build/' ]
10 silly lifecycle personal-site@2.1.0~predeploy: Returned: code: 1  signal: null
11 info lifecycle personal-site@2.1.0~predeploy: Failed to exec predeploy script
12 verbose stack Error: personal-site@2.1.0 predeploy: `npm run build && cp -r public/* build/`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:197:13)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:197:13)
12 verbose stack     at maybeClose (internal/child_process.js:988:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
13 verbose pkgid personal-site@2.1.0
14 verbose cwd /Users/kamel/Desktop/MYWebPage/Production
15 verbose Darwin 19.5.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
17 verbose node v11.12.0
18 verbose npm  v6.7.0
19 error code ELIFECYCLE
20 error errno 1
21 error personal-site@2.1.0 predeploy: `npm run build && cp -r public/* build/`
21 error Exit status 1
22 error Failed at the personal-site@2.1.0 predeploy script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by zzwonder** [comment]
had the same problem

**Comment by mldangelo** [comment]
Hi @Kamel773 and @zzwonder. I apologize for the delay in responding to your issues. There are a few things you can do here.

@zzwonder I was able to check out your fork of my repo and deploy it. Take a look at https://github.com/zzwonder/personal-site/blob/master/sample.env#L11 This line should be set in your `.env` file. You should also set https://github.com/zzwonder/personal-site/blob/master/package.json#L4 to your repository location. I also recommend triple checking your version `node --version` and making sure that it's set to at least 12 and preferably 14. Alternatively, you can rebase your changes on the main branch of this repo. I believe this error will be automatically resolved. 

@Kamel773 I'm sorry I wasn't able to help you in time. Your new site looks great. 

Going to close this issue. Please feel free to re-open it, or send me an email: michael.l.dangelo@gmail.com if you'd like some 1-1 help.
