### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by kendrickassignemt** [mldangelo/personal-site#247]
I've done all the step you've given and when i run this script `npm run dev` it gave me
`npm run dev

> personal-site@2.1.0 dev
> nodemon server/server.js --ignore app/ --ignore test/ --exec babel-node

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node server/server.js`
'babel-node' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...`

and it stucked

what i done is 
- restart the command tools i used
- cd `C:/User/personal-site`
- `npm install babel-cli`

Still got the same issues. How do i fix it. Thanks

**Comment by patelchandan** [comment]
i also got same error

**Comment by patelchandan** [comment]
if you got solution then help me please

**Comment by mldangelo** [comment]
Hi @kendrickassignemt and @patelchandan. I'm so sorry for my delay in responding to your issues. I spent some time cleaning up the main branch of this repository and converted the site to use create-react-app (no more babel-cli or nodemon dependencies). If you would still like help with getting my site up and running, please feel free to re-open this issue or send me an email at michael.l.dangelo@gmail.com.
