### ISSUE TITLE
github page showing README

### ISSUE THREAD

**Issue by masapasa** [mldangelo/personal-site#259]
Why is my github page only showing readme?
github.com/masapasa/personal-site
I appreciate any hep

**Comment by mldangelo** [comment]
Hi, if I 

```bash 
curl https://masapasa.github.io/personal-site/
```

I get
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
followed by a redirect to `http://www.teslamusk.site/`, which renders the readme with jekyll. This means that you should check your settings menu and make sure you're rendering the gh-pages branch. I'll make a PR shortly to your repo with some other minor configuration issues.

**Comment by mldangelo** [comment]
On further inspection after visiting https://www.teslamusk.co/, it also looks like you may need to update your DNS, please take a quick look at adding an A record here: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site Mine looks like this: 

<img width="1039" alt="Screen Shot 2020-12-30 at 9 31 48 AM" src="https://user-images.githubusercontent.com/7235481/103357721-e188af00-4a81-11eb-943b-52bf3a7f633f.png">

**Comment by mldangelo** [comment]
Closing. Please feel free to email me: michael.l.dangelo@gmail.com or re-open the issue if you still need help.
