### ISSUE TITLE
Not able to modify my name in Navbar

### ISSUE THREAD

**Issue by noobcoder486** [mldangelo/personal-site#261]
The Navbar which holds all the navigation tabs like Resume, About, etc has one more named Michael D'Angelo at the start. I want to change it to my name. I searched all files but I failed to found exactly where it is located. Please help me to change the name.
![Screenshot from 2021-01-07 18-19-19](https://user-images.githubusercontent.com/61982645/103894814-7429ed80-5115-11eb-9053-e5378dfb3f35.jpg)

**Comment by mldangelo** [comment]
For everyone else reading this, routes displayed in the navbar and the hamburger menu are defined here: https://github.com/mldangelo/personal-site/blob/main/src/data/routes.js
