### ISSUE TITLE
Deploying the Project on Github pages

### ISSUE THREAD

**Issue by noobcoder486** [mldangelo/personal-site#262]
Hello,
First of all, I would like to thank @mldangelo for developing such a wonderful site. I have completely modified this project as per my wish and now I want to deploy in through GitHub pages. I don't have any prior knowledge related to hosting and also GitHub pages.  Can someone help me step wise in deploying this project through my GitHub repository.Even step wise explanation will do.
I am a student from India and this project helped me showcase my resume and skill in a creative way.
A heart-full regards to all contributors and thank you in advance to help me deploying this project. :)

**Comment by mldangelo** [comment]
I'm helping @noobcoder486 offline. For other people looking for more information outside of my [readme](https://github.com/mldangelo/personal-site#deploying) and [adapting guide](https://github.com/mldangelo/personal-site/blob/main/docs/adapting-guide.md), I recommend reading about how github pages work [here](https://pages.github.com/).
