### ISSUE TITLE
Broken links for Nearest Dollar and Cat Detector

### ISSUE THREAD

**Issue by charlesmorisset** [mldangelo/personal-site#264]
Hi Michael, 

I've started using your amazing website as the basis from mine (thanks a lot by the way!). 
In the process, I've noticed a couple of broken links on https://mldangelo.github.io/personal-site/projects: 
* Nearest Dollar points to https://mldangelo.github.io/projects/nearestdollar/, which is 404
* Cat Detector points to https://mldangelo.github.io/project/catdetector/, which is also 404.

**Comment by mldangelo** [comment]
Hi @charlesmorisset Thank you for reporting my broken links. I temporarily disabled them. I'll rehost some version of these old projects in the future.
