### ISSUE TITLE
Deployment to Netlify

### ISSUE THREAD

**Issue by noworry-b-still** [mldangelo/personal-site#266]
I adapted this site. I tried to deploy it to Netlify. But it doesnt seems to be working. @mldangelo  can you make some documentation on how to deploy the site to Netlify?

**Comment by mldangelo** [comment]
Hi @Tesla-Atoz, I don't officially support Netlify yet. I will work on deployment instructions for Netlify for you.

**Comment by Tesla-Atoz** [comment]
Hey Mldangelo,

For me now, its not needed as I deployed the site to github pages. But I
think we should do that part (deployement instructions) for netlfy for
future purposes.

Thanks
