### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by Tesla-Atoz** [mldangelo/personal-site#267]
I followed the adapting.md guide and tried to deploy to githib pages . After running npm run build, it saying  Error: Failed to launch chrome!
[0128/222912.176:FATAL:feature_list.cc(254)] Check failed: !g_initilized_from_accessor.

What should i do? I am not understanding the troubleshooting here
[here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-windows)

**Comment by mldangelo** [comment]
Hi @Tesla-Atoz, thank you for reporting this issue. As you pointed out, this seems to be a Windows / Chrome issue.  Puppeteer is used by [react-snap](https://github.com/stereobooster/react-snap) to statically export pages, so I recommend looking there for help. I'm going to plan work over the coming weeks to make this project more friendly for windows developers.

**Comment by Tesla-Atoz** [comment]
Thanks for reply.

**Comment by Tesla-Atoz** [comment]
Hello @mldangelo  I solved the above issue by running the npm install twice. That made the deployment of my website to github pages.
