### ISSUE TITLE
Keeping The Header Menu Tags Highlighted.

### ISSUE THREAD

**Issue by mrkazmi333** [mldangelo/personal-site#271]
When a user clicks on a Menu button like About/Stats/etc apart from the Home page then that Tab should get highlighted until the user clicks on a different Tab or go back to Home. I would like to work on this if you want me to. do so 
Thanks :)

**Comment by mldangelo** [comment]
Hi @mrkazmi333, I'd love help on this. Thank you so much for offering. You may find the following links helpful:

- https://reactrouter.com/web/api/Hooks/uselocation - react router hook
- https://github.com/mldangelo/personal-site/blob/main/src/components/Template/Navigation.js - navbar component
- https://github.com/mldangelo/personal-site/blob/main/src/static/css/layout/_header.scss - where navbar styles are defined

**Comment by mldangelo** [comment]
Closing as stale.  Please feel free to re-open if this is still of interest to you.
