### ISSUE TITLE
Smooth Scroll in Resume Page

### ISSUE THREAD

**Issue by mrkazmi333** [mldangelo/personal-site#272]
If the site can have a smooth scroll when the user clicks on a certain option in this page like Experience/Education/Skills etc. It'll be  add to a great user experience as compared to current one which takes the user to that section in a flash.
I would be really happy to improve this and work on it.

**Comment by mldangelo** [comment]
Hi @mrkazmi333, I will also welcome this PR, as long as the scroll is relatively quick. You may be able to accomplish this with https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior Thank you so much for volunteering to help.
