### ISSUE TITLE
Github page not building

### ISSUE THREAD

**Issue by georgecma** [mldangelo/personal-site#279]
Hi Michael, thanks for this project. I've been adapting this for my personal website. I did an initial commit and the page with your info built fine at my github pages url. But when I modified it locally (it builds fine on localhost:3000) and git commit-pushed, github pages would not build. Was wondering if you have insight into why this is the case. Thanks

**Comment by DhruvDoshi** [comment]
Same issue with me. I think we need to change the path for the deployment. And other than that de we need to build before github page push?

**Comment by vijaysaravana** [comment]
Hi, @georgecma @DhruvDoshi 

This is happening because the gh-pages branch is not up-to-date. A simple rebase of `gh-pages` with `main` branch will solve this issue.

Reference:
https://lea.verou.me/2011/10/easily-keep-gh-pages-in-sync-with-master/

**Comment by georgecma** [comment]
Sorry forgot to reply to this thread, just wanted to say thanks, it works now! 

Best,
George
