### ISSUE TITLE
How can we remove "all" button from the skills 

### ISSUE THREAD

**Issue by DhruvDoshi** [mldangelo/personal-site#280]
I would like to remove this all button from the page 
![image](https://user-images.githubusercontent.com/41964565/117562979-69ca3100-b0c0-11eb-9d1c-ee10b3c86523.png)

**Comment by notrueblood** [comment]
Hey @DhruvDoshi, change line 81 in `src/components/Resume/Skills.js` from `{this.getButtons()}` to `          {this.getButtons().filter((b) => b.key !== 'All')}`

**Comment by notrueblood** [comment]
Closing w/solution provided. Feel free to reopen with any related follow up questions
