### ISSUE TITLE
[Bug] Website Title Not Rendered Correctly and Meta Description Is Not Set At All

### ISSUE THREAD

**Issue by rayliuca** [mldangelo/personal-site#285]
For some reason, in the src\layout\Main.js, the Main function cannot access the props.title and props.description variables (they are null at the time of building). I suspect this is some sort of async problem since they would appear after hot updates in the development environment. 

This leads to the symptom of the default title is used on all pages and none of them have the meta description tags. 

Using mldangelo.com for example, Michael D'Angelo is the title for all the pages and none of them have meta description tags.

![image](https://user-images.githubusercontent.com/35850903/118349608-d6a15900-b50e-11eb-987e-b837818c3939.png)

Not sure how to solve this tho

**Comment by rayliuca** [comment]
It appears this has something to do lazy loading. The tags would update properly if lazy loading is disabled. I imagine this is due to interactions between helmet and lazy, where the helmet scripts ran before the relevant chuck is loaded. 

For now, I disabled lazy loading on my site because the performance hit was minimal, but a better solution is needed.

**Comment by notrueblood** [comment]
Hey @rayliuca, fixing this in #288. Great bug report

**Comment by notrueblood** [comment]
Closing with merger of #288

**Comment by rayliuca** [comment]
Hi @notrueblood,

I took a closer look today and found that this still doesn't solve the issue for the meta description tag. The title was fixed, but not the meta description.

**Comment by rayliuca** [comment]
I tried to research helmet and react a bit more, but it appears to be very difficult if not impossible to make it work natively. The best way I can think of is to add an useEffect hook to a function that updates/adds the meta tag when the page finished loading/updating. Some relevant experts:

``` javascript

import { React, useEffect } from 'react';

function UpdateMetaDesc(MetaDec) {
  const MetaDescEle = document.querySelector('meta[name=description]');

  if (MetaDescEle) {
    if (MetaDescEle.getAttribute('content') !== MetaDec) {
      document.querySelector('meta[name="description"]').setAttribute('content', MetaDec);
    }
  } else {
    const meta = document.createElement('meta');
    meta.name = 'description';
    meta.content = MetaDec;
    document.getElementsByTagName('head')[0].appendChild(meta);
  }
}

const Main = (props) => {
  useEffect(() => {
    UpdateMetaDesc(props.description);
  });
  return (
    <HelmetProvider>
      <Analytics />
      <ScrollToTop />
      <div id="wrapper">
        <Navigation />
        <div id="main">
          {props.children}
        </div>
        {props.fullPage ? null : <SideBar />}
      </div>
      <Footer />
      <Helmet titleTemplate="Ray Liu | %s" defaultTitle="Ray Liu" defer={false}>
        {props.title && <title>{props.title}</title>}
        <meta name="description" content={props.description} />
      </Helmet>
    </HelmetProvider>
  );
};

```
