### ISSUE TITLE
Menu with yellow border on mobile

### ISSUE THREAD

**Issue by marcolino** [mldangelo/personal-site#287]
I don't know if this is a bug or a feature, but on mobile, clicking on hamburger, opens menu with a yellow border.
Clicking anywhere it disappears.
I would like to remove it completely.
Is it something related to accessibility?

**Comment by notrueblood** [comment]
Hi @marcolino, it is indeed for accessibility. To disable, change line 27 in `src/components/Template/Hamburger.js` to `<Menu right isOpen={open} disableAutoFocus>`

**Comment by notrueblood** [comment]
Closing as functionality is intended

**Comment by marcolino** [comment]
Perfect, thanks!
