### ISSUE TITLE
npm install fails.

### ISSUE THREAD

**Issue by devkigauravpal** [mldangelo/personal-site#290]
I am trying to try this out. I am zero in NPM/NVM so thought to follow the steps. I get this error. Any idea if I am missing anything?
verbose pkgid node-sass@4.14.1
3408 verbose cwd /Users/<user>/<path_to-dir>/personal-site
3409 verbose Darwin 19.6.0
3410 verbose argv "/usr/local/Cellar/node/16.3.0/bin/node" "/usr/local/bin/npm" "install"
3411 verbose node v16.3.0
3412 verbose npm  v7.16.0
3413 error code 1
3414 error path /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass
3415 error command failed
3416 error command sh -c node scripts/build.js
3417 error Building: /usr/local/Cellar/node/16.3.0/bin/node /Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
3418 error gyp info it worked if it ends with ok
3418 error gyp verb cli [
3418 error gyp verb cli   '/usr/local/Cellar/node/16.3.0/bin/node',
3418 error gyp verb cli   '/Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp/bin/node-gyp.js',
3418 error gyp verb cli   'rebuild',
3418 error gyp verb cli   '--verbose',
3418 error gyp verb cli   '--libsass_ext=',
3418 error gyp verb cli   '--libsass_cflags=',
3418 error gyp verb cli   '--libsass_ldflags=',
3418 error gyp verb cli   '--libsass_library='
3418 error gyp verb cli ]
3418 error gyp info using node-gyp@3.8.0
3418 error gyp info using node@16.3.0 | darwin | x64
3418 error gyp verb command rebuild []
3418 error gyp verb command clean []
3418 error gyp verb clean removing "build" directory
3418 error gyp verb command configure []
3418 error gyp verb check python checking for Python executable "python2" in the PATH
3418 error gyp verb `which` succeeded python2 /usr/bin/python2
3418 error gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
3418 error gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
3418 error gyp verb get node dir no --target version specified, falling back to host node version: 16.3.0
3418 error gyp verb command install [ '16.3.0' ]
3418 error gyp verb install input version string "16.3.0"
3418 error gyp verb install installing version: 16.3.0
3418 error gyp verb install --ensure was passed, so won't reinstall if already installed
3418 error gyp verb install version is already installed, need to check "installVersion"
3418 error gyp verb got "installVersion" 9
3418 error gyp verb needs "installVersion" 9
3418 error gyp verb install version is good
3418 error gyp verb get node dir target node version installed: 16.3.0
3418 error gyp verb build dir attempting to create "build" dir: /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass/build
3418 error gyp verb build dir "build" dir needed to be created? /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass/build
3418 error gyp verb build/config.gypi creating config file
3418 error gyp verb build/config.gypi writing out config file: /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass/build/config.gypi
3418 error (node:53532) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
3418 error (Use `node --trace-deprecation ...` to show where the warning was created)
3418 error gyp verb config.gypi checking for gypi file: /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass/config.gypi
3418 error gyp verb common.gypi checking for gypi file: /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass/common.gypi
3418 error gyp verb gyp gyp format was not specified; forcing "make"
3418 error gyp info spawn /usr/bin/python2
3418 error gyp info spawn args [
3418 error gyp info spawn args   '/Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp/gyp/gyp_main.py',
3418 error gyp info spawn args   'binding.gyp',
3418 error gyp info spawn args   '-f',
3418 error gyp info spawn args   'make',
3418 error gyp info spawn args   '-I',
3418 error gyp info spawn args   '/Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass/build/config.gypi',
3418 error gyp info spawn args   '-I',
3418 error gyp info spawn args   '/Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp/addon.gypi',
3418 error gyp info spawn args   '-I',
3418 error gyp info spawn args   '/Users/<user>/.node-gyp/16.3.0/include/node/common.gypi',
3418 error gyp info spawn args   '-Dlibrary=shared_library',
3418 error gyp info spawn args   '-Dvisibility=default',
3418 error gyp info spawn args   '-Dnode_root_dir=/Users/<user>/.node-gyp/16.3.0',
3418 error gyp info spawn args   '-Dnode_gyp_dir=/Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp',
3418 error gyp info spawn args   '-Dnode_lib_file=/Users/<user>/.node-gyp/16.3.0/<(target_arch)/node.lib',
3418 error gyp info spawn args   '-Dmodule_root_dir=/Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass',
3418 error gyp info spawn args   '-Dnode_engine=v8',
3418 error gyp info spawn args   '--depth=.',
3418 error gyp info spawn args   '--no-parallel',
3418 error gyp info spawn args   '--generator-output',
3418 error gyp info spawn args   'build',
3418 error gyp info spawn args   '-Goutput_dir=.'
3418 error gyp info spawn args ]
3418 error No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
3418 error
3418 error No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
3418 error
3418 error No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
3418 error
3418 error gyp: No Xcode or CLT version detected!
3418 error gyp ERR! configure error
3418 error gyp ERR! stack Error: `gyp` failed with exit code: 1
3418 error gyp ERR! stack     at ChildProcess.onCpExit (/Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp/lib/configure.js:345:16)
3418 error gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
3418 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
3418 error gyp ERR! System Darwin 19.6.0
3418 error gyp ERR! command "/usr/local/Cellar/node/16.3.0/bin/node" "/Users/<user>/<path_to-dir>/personal-site/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3418 error gyp ERR! cwd /Users/<user>/<path_to-dir>/personal-site/node_modules/node-sass
3418 error gyp ERR! node -v v16.3.0
3418 error gyp ERR! node-gyp -v v3.8.0
3418 error gyp ERR! not ok
3418 error Build failed with error code: 1
3419 verbose exit 1

**Comment by bsgrigorov** [comment]
try `nvm install` if it fails upgrade your node version and run `nvm install` and then `npm install`.

**Comment by DhruvDoshi** [comment]
When I tried to get the latest packages in package.json, It worked completely fine on the local system but the work flows are failing. there is some kind of errors which says like, npm ERR! fsevents not accessible from jest-haste-map


Please suggest me any update if you think it is necessary!

**Comment by KirubelAfrassa** [comment]
Had the same problem with the latest node v16, when I switched to node v12 using nvm the problem was solved. `nvm install v12`
