### ISSUE TITLE
PAGES FAILING FOR NEW PACKAGE.JSON

### ISSUE THREAD

**Issue by DhruvDoshi** [mldangelo/personal-site#293]
On local system the code is running fine but when I try to host it on git hub pages it was repetitively showing this kind of errors

![image](https://user-images.githubusercontent.com/41964565/141016066-42f0c7ef-2d81-41f5-83a5-2b48706d210f.png)

If someone could help me with this please let me know.

**Comment by mldangelo** [comment]
Closing. Please let me know if you are still encountering this issue after the latest update.
