### ISSUE TITLE
Deploying from a Fork to GH Pages with Workflow

### ISSUE THREAD

**Issue by jwallace145** [mldangelo/personal-site#315]
Hello,

I recently forked this repository and attempted to deploy to GitHub pages using the included [`github-pages.yml`](https://github.com/mldangelo/personal-site/blob/main/.github/workflows/github-pages.yml) workflow but encountered some difficulties.

I believe the workflow doesn't work from a fork because forked repositories change the permissions granted to the `GITHUB_TOKEN`. This causes the workflow to get a permission denied error when attempting to write to the repository. See this [documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) for default permissions granted to the `GITHUB_TOKEN` for forked repositories.

I tried to explicitly elevate the permissions for the workflow but was unable to do so successfully. 

To resolve, I deleted the `.git` folder and made a new repository from scratch and pushed my changes to the new repository. Then, I was able to run the workflow successfully without getting the permission denied error but the site was still not displaying at my homepage URL. So, I went to the repository settings and changed the GitHub Page settings to deploy from a branch (specifically the `gh-pages` branch) because the `gh-pages -d build` deploy command seems to build the site in this branch with the entry point being the `index.html` in the root folder. After these updates, the site was successfully displaying via the homepage URL.

I am raising this issue just for awareness and would love to contribute back to the `README.md` if you think this is a valid issue.

Thanks

**Comment by jwallace145** [comment]
I see that there was a note included about the `gh-pages` in the [`adapting-guide.md`](https://github.com/mldangelo/personal-site/blob/main/docs/adapting-guide.md). So scratch that :) 

I think the `GITHUB_TOKEN` issues are still valid for forked repositories though.

**Comment by thesanju** [comment]
![Screenshot from 2023-07-29 10-50-11](https://github.com/mldangelo/personal-site/assets/130161177/cb3ec3bb-f421-426d-8b26-70c170d8e686)
### Getting error while npm run deploy
please help

**Comment by mldangelo** [comment]
I just updated the site to use https://github.com/actions/deploy-pages, which should resolve your issues. Please feel free to comment if you still need help!

**Comment by thesanju** [comment]
> I just updated the site to use https://github.com/actions/deploy-pages, which should resolve your issues. Please feel free to comment if you still need help!

it's working now thanks for the help.
