### ISSUE TITLE
Deployment timing out

### ISSUE THREAD

**Issue by AdityaRoot** [mldangelo/personal-site#329]
Hiya! I've been having trouble updating my site since mid December 2022 and I wanted to post an issue to ask for help! I believe that this isn't an issue solely on my part, though I do think it can be fixed locally - just not sure how.

From around mid December 2022 I believe an update was pushed to either github actions or general package managers which breaks the workflow actions deployment scripts.

For a description of the issue directly, my following links are relevant:
https://github.com/AdityaRoot/adityaroot.github.io/actions - My actions log
https://github.com/AdityaRoot/adityaroot.github.io/actions/runs/3567353595 - My most recent successful run of the deployment workflow
https://github.com/AdityaRoot/adityaroot.github.io/actions/runs/3567353605 - My most recent successful run of the Node.js CI workflow (from the same commit as the previous link)

https://github.com/AdityaRoot/adityaroot.github.io/actions/runs/3751270615 - My first unsuccessful deployment run
https://github.com/AdityaRoot/adityaroot.github.io/actions/runs/3751270620 - My first unsuccessful Node.js CI run (same commit as previous link)

(If relevant/helpful, here are my most recent failed runs for [deployment ](https://github.com/AdityaRoot/adityaroot.github.io/actions/runs/4112599839) and [node.js](https://github.com/AdityaRoot/adityaroot.github.io/actions/runs/4112599841), both were cancelled early once they got hung at the same point)

~~Through my commit history multiple different attempted fixes can be seen~~ (nvm did a hard reset to previous commit to try and fix, didnt work either :')), from trying to statically update the gh-pages branch to removing support for version 14.x

The specific issue point seems to be on the Building step (titled Build and Statically Render for Node, and Build and Deploy for deployment), where while after the line
```
  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment
```
The working actions shows 
```
💬  console.log at /: [react-ga] gaTrackingID is required in initialize()
✅  crawled 1 out of 7 (/)
️️️💬  console.log at /404.html: [react-ga] gaTrackingID is required in initialize()
️️️💬  console.log at /about: [react-ga] gaTrackingID is required in initialize()
️️️💬  console.log at /resume: [react-ga] gaTrackingID is required in initialize()
️️️💬  console.log at /projects: [react-ga] gaTrackingID is required in initialize()
✅  crawled 2 out of 7 (/about)
✅  crawled 3 out of 7 (/resume)
️️️💬  console.log at /stats: [react-ga] gaTrackingID is required in initialize()
✅  crawled 4 out of 7 (/projects)
✅  crawled 5 out of 7 (/404.html)
️️️💬  console.log at /contact: [react-ga] gaTrackingID is required in initialize()
✅  crawled 6 out of 7 (/stats)
✅  crawled 7 out of 7 (/contact)

> personal-site@4.0.0 deploy
> gh-pages -d build

Published
```

The broken workflow simply times out after 6 hours (the github workflow time limit for my account).

In order to provide greater detail about the changes between the old and new script, I have provided the outputs of diff files for Node.CI version 16.x and the deployment build below as files. Note that I cut off the working files after the line `https://cra.link/deployment` to make the output cleaner, as the workflow breaks before then.
[diff_deployment.txt](https://github.com/mldangelo/personal-site/files/10674379/diff_deployment.txt)
[diff_16x.txt](https://github.com/mldangelo/personal-site/files/10674382/diff_16x.txt)

I believe that this is an issue not solely on my end because in going through recently updated forks of the project, I have found multiple users suffering from the same issue, all starting around the same time. Some examples are:
https://github.com/tyhmas/personal-website/actions Who started their site only recently and has mainly only failed actions
https://github.com/bsgrigorov/personal-site/actions Who I believe based on their updated readme is manually deploying their site using node 14.18.1
https://github.com/DhruvDoshi/dhruvdoshi.github.io/actions?page=3 Who in their older commits (as they commit a lot) can be seen having the same issue, however also having managed to fix the issue.

I have been unable to replicate how @DhruvDoshi managed to fix their issue however, and believe they are also using Netlify to host their website.

I'm very much a novice with web development so would greatly appreciate any and all help!

**Comment by Smartmayukh** [comment]
Hey I am facing the same problem. Have you found the solution to this problem ???

**Comment by KevinIsMyName** [comment]
> Hey I am facing the same problem. Have you found the solution to this problem ???

[Some other user](https://stackoverflow.com/a/74925043) are reporting that it has something to do with GitHub's ubuntu-latest changing from 20.04 to 22.04.

I tried it too [here](https://github.com/KevinIsMyName/personal-site/actions/runs/4347171027) and it looks like it's fixed.

I don't know what the permanent solution is but this is definitely a temporary fix. My guess is how GitHub handles running jobs on the newest ubuntu 20.04 but I can't say anything for sure.

**Comment by mldangelo** [comment]
Hi everyone! Sorry for my delay. I'll have a fix for this later today.

**Comment by mldangelo** [comment]
Hi @KevinIsMyName @Smartmayukh and @AdityaRoot, it should be fixed now. Please feel free to re-open the issue if you experience problems. I'm going to go through an open a few small cleanup PRs aimed at making the development experience better.

**Comment by Smartmayukh** [comment]
Thank you so much for helping us out 😊😊
