### ISSUE TITLE
Minified React error #418; #423; in production build

### ISSUE THREAD

**Issue by safwanidrees** [mldangelo/personal-site#467]
![Screenshot 2023-11-12 at 4 25 50 PM](https://github.com/mldangelo/personal-site/assets/38593104/f0b5468c-e2bd-4536-9c7c-186df5b0d236)

**Comment by safwanidrees** [comment]
How to fix Minified React error #418; #423; issue in the production build of that repository ?

**Comment by abz98** [comment]
问题描述
当我试图拖拽一个节点到树图的另一个节点下时，使用changeData改变了数据后。由于我节点上绑定了鼠标mouseleave等事件，当触发了mouseleave里的updateItem方法，报错了，有什么解法吗？

重现链接
https://codesandbox.io/p/sandbox/g6-test-yts46l?file=%2Fsrc%2FApp.tsx%3A71%2C22

重现步骤
在codesanbox中预览页面
直接在画布中拖拽任一节点
鼠标移动几下
报错了
预期行为
期望有什么办法可以不报错

平台
操作系统: [macOS, Windows, Linux, React Native ...]
网页浏览器: [Google Chrome, Safari, Firefox]
G6 版本: [4.5.1 ... ]
屏幕截图或视频（可选）
