### ISSUE TITLE
Page is showing readme file

### ISSUE THREAD

**Issue by yoouzee** [mldangelo/personal-site#546]
Hi! Anyone knows how to fix this issue?

**Comment by minyan8** [comment]
Have you solved this issue?

**Comment by mldangelo** [comment]
hi @minyan8 and @yoouzee can you please give more context on your exact issue? Feel free to book a time on my calendar if you would like to show me https://cal.com/michael-dangelo/15min?month=2024-08

**Comment by minyan8** [comment]
Hi, @mldangelo . I set the repository's name to {username}.github.io and updated the homepage and repository values in the package.json file. I also deleted the CNAME file. After deploying it to GitHub Pages, the website only displays the README file.

**Comment by mldangelo** [comment]
Go to settings, then pages. Check your build and deployment source. Please let me know if this doesn't solve your issue. 

<img width="1152" alt="Screenshot 2024-08-11 at 10 25 28 PM" src="https://github.com/user-attachments/assets/7d3ee2b8-2d7c-4489-96a6-b2dd10003885">

**Comment by minyan8** [comment]
I have solved this issue based on the screenshot you provided. Thanks for your time and help!
